global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'basic-apm-test'
    static_configs:
      - targets: [ 'localhost:8080' ]  # Replace with your application's address
        metrics_path: '/actuator/prometheus'
